name: PHPUnit

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.2'
            composer-flags: '--with "drupal/core:^10" --with "phpunit/phpunit:^9.6"'
          - php-version: '8.3'
            composer-flags: ''
          - php-version: '8.4'
            composer-flags: ''
          - php-version: '8.5'
            composer-flags: ''
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist ${{ matrix.composer-flags }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Download Infection PHAR
        run: |
          wget https://github.com/infection/infection/releases/download/0.32.3/infection.phar
          wget https://github.com/infection/infection/releases/download/0.32.3/infection.phar.asc

      - name: Validate Infection PHAR
        run: |
          gpg --keyserver hkps://keys.openpgp.org --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0
          gpg --with-fingerprint --verify infection.phar.asc infection.phar
          chmod +x infection.phar

      - name: Run mutation testing
        run: ./infection.phar --threads=max --min-msi=100 --min-covered-msi=100
